apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-service.fullname" . }}-secrets
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.secrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
