// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitGoogleAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGoogleAuthRequest) Reset() {
	*x = InitGoogleAuthRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGoogleAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGoogleAuthRequest) ProtoMessage() {}

func (x *InitGoogleAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGoogleAuthRequest.ProtoReflect.Descriptor instead.
func (*InitGoogleAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{0}
}

type InitGoogleAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CodeChallenge string                 `protobuf:"bytes,3,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGoogleAuthResponse) Reset() {
	*x = InitGoogleAuthResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGoogleAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGoogleAuthResponse) ProtoMessage() {}

func (x *InitGoogleAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGoogleAuthResponse.ProtoReflect.Descriptor instead.
func (*InitGoogleAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{1}
}

func (x *InitGoogleAuthResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *InitGoogleAuthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InitGoogleAuthResponse) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

type LoginGoogleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGoogleRequest) Reset() {
	*x = LoginGoogleRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGoogleRequest) ProtoMessage() {}

func (x *LoginGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGoogleRequest.ProtoReflect.Descriptor instead.
func (*LoginGoogleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{2}
}

func (x *LoginGoogleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginGoogleRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{3}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ViolationCount int32                  `protobuf:"varint,5,opt,name=violation_count,json=violationCount,proto3" json:"violation_count,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{7}
}

func (x *AccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountResponse) GetViolationCount() int32 {
	if x != nil {
		return x.ViolationCount
	}
	return 0
}

func (x *AccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUpgradeRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpgradeRequestsRequest) Reset() {
	*x = ListUpgradeRequestsRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpgradeRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpgradeRequestsRequest) ProtoMessage() {}

func (x *ListUpgradeRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpgradeRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListUpgradeRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ListUpgradeRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUpgradeRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUpgradeRequestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpgradeRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ReviewedBy    string                 `protobuf:"bytes,6,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeRequestItem) Reset() {
	*x = UpgradeRequestItem{}
	mi := &file_api_proto_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeRequestItem) ProtoMessage() {}

func (x *UpgradeRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeRequestItem.ProtoReflect.Descriptor instead.
func (*UpgradeRequestItem) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{9}
}

func (x *UpgradeRequestItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpgradeRequestItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpgradeRequestItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpgradeRequestItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpgradeRequestItem) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *UpgradeRequestItem) GetReviewedBy() string {
	if x != nil {
		return x.ReviewedBy
	}
	return ""
}

func (x *UpgradeRequestItem) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

func (x *UpgradeRequestItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUpgradeRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*UpgradeRequestItem  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpgradeRequestsResponse) Reset() {
	*x = ListUpgradeRequestsResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpgradeRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpgradeRequestsResponse) ProtoMessage() {}

func (x *ListUpgradeRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpgradeRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListUpgradeRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{10}
}

func (x *ListUpgradeRequestsResponse) GetData() []*UpgradeRequestItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListUpgradeRequestsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUpgradeRequestsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUpgradeRequestsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RequestUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpgradeRequest) Reset() {
	*x = RequestUpgradeRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpgradeRequest) ProtoMessage() {}

func (x *RequestUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpgradeRequest.ProtoReflect.Descriptor instead.
func (*RequestUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{11}
}

func (x *RequestUpgradeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApproveUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveUpgradeRequest) Reset() {
	*x = ApproveUpgradeRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveUpgradeRequest) ProtoMessage() {}

func (x *ApproveUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveUpgradeRequest.ProtoReflect.Descriptor instead.
func (*ApproveUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveUpgradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectUpgradeRequest) Reset() {
	*x = RejectUpgradeRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectUpgradeRequest) ProtoMessage() {}

func (x *RejectUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectUpgradeRequest.ProtoReflect.Descriptor instead.
func (*RejectUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RejectUpgradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectUpgradeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockAccountRequest) Reset() {
	*x = LockAccountRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAccountRequest) ProtoMessage() {}

func (x *LockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockAccountRequest.ProtoReflect.Descriptor instead.
func (*LockAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{14}
}

func (x *LockAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LockAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnlockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockAccountRequest) Reset() {
	*x = UnlockAccountRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAccountRequest) ProtoMessage() {}

func (x *UnlockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAccountRequest.ProtoReflect.Descriptor instead.
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{15}
}

func (x *UnlockAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{16}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_identity_proto protoreflect.FileDescriptor

const file_api_proto_identity_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/identity.proto\x12\videntity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15InitGoogleAuthRequest\"p\n" +
	"\x16InitGoogleAuthResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12%\n" +
	"\x0ecode_challenge\x18\x03 \x01(\tR\rcodeChallenge\">\n" +
	"\x12LoginGoogleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"v\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc7\x01\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fviolation_count\x18\x05 \x01(\x05R\x0eviolationCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x1aListUpgradeRequestsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xab\x02\n" +
	"\x12UpgradeRequestItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\x12\x1f\n" +
	"\vreviewed_by\x18\x06 \x01(\tR\n" +
	"reviewedBy\x12;\n" +
	"\vreviewed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x99\x01\n" +
	"\x1bListUpgradeRequestsResponse\x123\n" +
	"\x04data\x18\x01 \x03(\v2\x1f.identity.v1.UpgradeRequestItemR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"/\n" +
	"\x15RequestUpgradeRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"'\n" +
	"\x15ApproveUpgradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14RejectUpgradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"<\n" +
	"\x12LockAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"&\n" +
	"\x14UnlockAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9a\a\n" +
	"\x0fIdentityService\x12J\n" +
	"\n" +
	"GetAccount\x12\x1e.identity.v1.GetAccountRequest\x1a\x1c.identity.v1.AccountResponse\x12h\n" +
	"\x13ListUpgradeRequests\x12'.identity.v1.ListUpgradeRequestsRequest\x1a(.identity.v1.ListUpgradeRequestsResponse\x12R\n" +
	"\x0eRequestUpgrade\x12\".identity.v1.RequestUpgradeRequest\x1a\x1c.identity.v1.MessageResponse\x12R\n" +
	"\x0eApproveUpgrade\x12\".identity.v1.ApproveUpgradeRequest\x1a\x1c.identity.v1.MessageResponse\x12P\n" +
	"\rRejectUpgrade\x12!.identity.v1.RejectUpgradeRequest\x1a\x1c.identity.v1.MessageResponse\x12L\n" +
	"\vLockAccount\x12\x1f.identity.v1.LockAccountRequest\x1a\x1c.identity.v1.MessageResponse\x12P\n" +
	"\rUnlockAccount\x12!.identity.v1.UnlockAccountRequest\x1a\x1c.identity.v1.MessageResponse\x12Y\n" +
	"\x0eInitGoogleAuth\x12\".identity.v1.InitGoogleAuthRequest\x1a#.identity.v1.InitGoogleAuthResponse\x12J\n" +
	"\vLoginGoogle\x12\x1f.identity.v1.LoginGoogleRequest\x1a\x1a.identity.v1.TokenResponse\x12L\n" +
	"\fRefreshToken\x12 .identity.v1.RefreshTokenRequest\x1a\x1a.identity.v1.TokenResponse\x12B\n" +
	"\x06Logout\x12\x1a.identity.v1.LogoutRequest\x1a\x1c.identity.v1.MessageResponseBMZKgithub.com/rent-a-girlfriend/identity-service/api/proto/identity;identityv1b\x06proto3"

var (
	file_api_proto_identity_proto_rawDescOnce sync.Once
	file_api_proto_identity_proto_rawDescData []byte
)

func file_api_proto_identity_proto_rawDescGZIP() []byte {
	file_api_proto_identity_proto_rawDescOnce.Do(func() {
		file_api_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_identity_proto_rawDesc), len(file_api_proto_identity_proto_rawDesc)))
	})
	return file_api_proto_identity_proto_rawDescData
}

var file_api_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_identity_proto_goTypes = []any{
	(*InitGoogleAuthRequest)(nil),       // 0: identity.v1.InitGoogleAuthRequest
	(*InitGoogleAuthResponse)(nil),      // 1: identity.v1.InitGoogleAuthResponse
	(*LoginGoogleRequest)(nil),          // 2: identity.v1.LoginGoogleRequest
	(*TokenResponse)(nil),               // 3: identity.v1.TokenResponse
	(*RefreshTokenRequest)(nil),         // 4: identity.v1.RefreshTokenRequest
	(*LogoutRequest)(nil),               // 5: identity.v1.LogoutRequest
	(*GetAccountRequest)(nil),           // 6: identity.v1.GetAccountRequest
	(*AccountResponse)(nil),             // 7: identity.v1.AccountResponse
	(*ListUpgradeRequestsRequest)(nil),  // 8: identity.v1.ListUpgradeRequestsRequest
	(*UpgradeRequestItem)(nil),          // 9: identity.v1.UpgradeRequestItem
	(*ListUpgradeRequestsResponse)(nil), // 10: identity.v1.ListUpgradeRequestsResponse
	(*RequestUpgradeRequest)(nil),       // 11: identity.v1.RequestUpgradeRequest
	(*ApproveUpgradeRequest)(nil),       // 12: identity.v1.ApproveUpgradeRequest
	(*RejectUpgradeRequest)(nil),        // 13: identity.v1.RejectUpgradeRequest
	(*LockAccountRequest)(nil),          // 14: identity.v1.LockAccountRequest
	(*UnlockAccountRequest)(nil),        // 15: identity.v1.UnlockAccountRequest
	(*MessageResponse)(nil),             // 16: identity.v1.MessageResponse
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
}
var file_api_proto_identity_proto_depIdxs = []int32{
	17, // 0: identity.v1.AccountResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: identity.v1.UpgradeRequestItem.reviewed_at:type_name -> google.protobuf.Timestamp
	17, // 2: identity.v1.UpgradeRequestItem.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: identity.v1.ListUpgradeRequestsResponse.data:type_name -> identity.v1.UpgradeRequestItem
	6,  // 4: identity.v1.IdentityService.GetAccount:input_type -> identity.v1.GetAccountRequest
	8,  // 5: identity.v1.IdentityService.ListUpgradeRequests:input_type -> identity.v1.ListUpgradeRequestsRequest
	11, // 6: identity.v1.IdentityService.RequestUpgrade:input_type -> identity.v1.RequestUpgradeRequest
	12, // 7: identity.v1.IdentityService.ApproveUpgrade:input_type -> identity.v1.ApproveUpgradeRequest
	13, // 8: identity.v1.IdentityService.RejectUpgrade:input_type -> identity.v1.RejectUpgradeRequest
	14, // 9: identity.v1.IdentityService.LockAccount:input_type -> identity.v1.LockAccountRequest
	15, // 10: identity.v1.IdentityService.UnlockAccount:input_type -> identity.v1.UnlockAccountRequest
	0,  // 11: identity.v1.IdentityService.InitGoogleAuth:input_type -> identity.v1.InitGoogleAuthRequest
	2,  // 12: identity.v1.IdentityService.LoginGoogle:input_type -> identity.v1.LoginGoogleRequest
	4,  // 13: identity.v1.IdentityService.RefreshToken:input_type -> identity.v1.RefreshTokenRequest
	5,  // 14: identity.v1.IdentityService.Logout:input_type -> identity.v1.LogoutRequest
	7,  // 15: identity.v1.IdentityService.GetAccount:output_type -> identity.v1.AccountResponse
	10, // 16: identity.v1.IdentityService.ListUpgradeRequests:output_type -> identity.v1.ListUpgradeRequestsResponse
	16, // 17: identity.v1.IdentityService.RequestUpgrade:output_type -> identity.v1.MessageResponse
	16, // 18: identity.v1.IdentityService.ApproveUpgrade:output_type -> identity.v1.MessageResponse
	16, // 19: identity.v1.IdentityService.RejectUpgrade:output_type -> identity.v1.MessageResponse
	16, // 20: identity.v1.IdentityService.LockAccount:output_type -> identity.v1.MessageResponse
	16, // 21: identity.v1.IdentityService.UnlockAccount:output_type -> identity.v1.MessageResponse
	1,  // 22: identity.v1.IdentityService.InitGoogleAuth:output_type -> identity.v1.InitGoogleAuthResponse
	3,  // 23: identity.v1.IdentityService.LoginGoogle:output_type -> identity.v1.TokenResponse
	3,  // 24: identity.v1.IdentityService.RefreshToken:output_type -> identity.v1.TokenResponse
	16, // 25: identity.v1.IdentityService.Logout:output_type -> identity.v1.MessageResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_identity_proto_init() }
func file_api_proto_identity_proto_init() {
	if File_api_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_identity_proto_rawDesc), len(file_api_proto_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_identity_proto_goTypes,
		DependencyIndexes: file_api_proto_identity_proto_depIdxs,
		MessageInfos:      file_api_proto_identity_proto_msgTypes,
	}.Build()
	File_api_proto_identity_proto = out.File
	file_api_proto_identity_proto_goTypes = nil
	file_api_proto_identity_proto_depIdxs = nil
}
